---
title: rCharts NYT Interactive Home Price
author: Timely Portfolio  (all credit to NYTimes)
github: {user: timelyportfolio, repo: rCharts_nyt_home_price, branch: "gh-pages"}
framework: bootstrap
mode: selfcontained
widgets: "nyt_home"
highlighter: prettify
hitheme: twitter-bootstrap
lead : >
  NYT's Home Price Visualization with rCharts
---

# Disclaimer and Attribution

**I claim absolutely no credit for this visualization, which I consider one of the most instructive I have ever seen.  If anybody believes this to be not fair use, I will take it down immediately.  I am implicitly assuming approval for this due to the interview http://datastori.es/data-stories-22-nyt-graphics-and-d3-with-mike-bostock-and-shan-carter/.** 

```{r echo=F, warning= F, message=F}
opts_chunk$set(message = FALSE, warning = FALSE, error = FALSE, tidy = FALSE, cache = FALSE,results = 'asis' )
```

---
# Another Favorite from NYT
  


---
# Reusable Version in rCharts

```{r results = 'asis'}
require(rCharts)

p1 <- rCharts$new()
p1$field(
  "LIB",
  list(url = paste0(getwd(),"/libraries/widgets/nyt_home"), name = "")
)
p1$field(
  'templates', 
  modifyList(
    p1$templates,
    list( #page = "rChart_nyt_home.html",
      script = "libraries/widgets/nyt_home/layouts/nyt_home.html")
  )
)
p1$set(description = "The Standard & Poor's Case-Shiller Home Price Index for 20 major metropolitan areas is one of the most closely watched gauges of the housing market. The figures for April were released June 25. Figures shown here are not seasonally adjusted or adjusted for inflation.")

#get the data and convert to a format that we would expect from melted xts
#will be typical
#also original only uses a single value (val) and not other 
data <- read.csv("data/case-shiller-tiered2.csv", stringsAsFactors = F)

data.melt <- data.frame(
  format(as.Date(paste(data[,3],data[,4],"01",sep="-"),format = "%Y-%m-%d")),
  data[,c(1,2,5)]
)
colnames(data.melt) <- c("date",colnames(data.melt)[-1])


p1$set(data = data.melt)
cat(noquote(p1$html()))
```